// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type RegisterUser struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserFilter struct {
	ID       *string `json:"id"`
	Username *string `json:"username"`
}
